server:
  port: 80
#  ssl:
#    key-store: classpath:aull99.jks
#    key-store-password: aull99
#    key-store-type: JKS
#    enabled: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://liulian.auzero.top:3306/ourcity?serverTimezone=Asia/Shanghai
    username: root
    password: auzero009

  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-wait: -1
        max-active: 8
